### ISSUE TITLE
--net argument and testing?

### ISSUE THREAD

**Issue by GustelDE** [b3nn0/ogn2dump1090#6]
Hi, in the documentation is stated:

**This requires an already running dump1090-mutability or dump1090-fa instance with the --net argument.**

I have this default stuff in there:
 /usr/bin/dump1090-fa --quiet --device-type rtlsdr --device-index 10900001 --gain 60 --adaptive-range --fix --lat 47.xxxxx --lon 11.xxxxx --max-range 360 --net-ro-port 30002 --net-sbs-port 30003 --net-bi-port 30004,30104 --net-bo-port 30005 --json-location-accuracy 1 --write-json /run/dump1090-fa

Is this correct? If not, where (and what) do I have change?
And is there a way to test the injection of OGN-data into dump1090 in some way?

Thanks

**Comment by b3nn0** [comment]
It connects to beast port 30004, so your command should work, yes.
Testing: well.. by transmitting something that the OGN receiver can receive. E.g. an esp32-ogn-tracker.

**Comment by GustelDE** [comment]
Thanks! I understand it so: --net-bi-port stands for Beast-In? If true, ogn-injected data are going then out via --net-bo-port 30005 (bo = Beast-Out?)? VRS listens on port 30005, I assume tar1090 must listen on some of the 3000x-ports too.
