### ISSUE TITLE
VRS and tar1090?

### ISSUE THREAD

**Issue by GustelDE** [b3nn0/ogn2dump1090#7]
Hi,

is my assumption correct: ogn2dump1090 will inject (OGN) data into dump1090 and this will ouput the OGN-data to VRS (Virtual Rsadar Server) and tar1090 in the same stream as the regular decoded ADS-B-data goes out?

Will this OGN-traffic in tar1090 then marked as ADS-B or UAT...??

**Comment by b3nn0** [comment]
It will be injected like MLAT traffic, so will be visible in tar1090. Don't know about VRS.
